config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    resources :comments, only: [ :show, :create ]
    resources :things, only: [:index, :show, :create]
  end

  devise_for :users
  resources :things do
    collection do
      get :queue
    end
  end

  resources :comments, only: [:update, :destroy]

  root to: "things#index"
end

app/models/comment.rb
require 'routing'

class Comment < ApplicationRecord
  include Routing

  belongs_to :thing
  after_create :email_owner, :notify_slack

  validates :text, :name, :email, presence: true

  scope :published, -> { where(published: true) }

  def as_slack_attachment
    {
      fallback: "Kommentar av #{self.name}: '#{self.text}'",
      text: "<#{thing_url(self.thing)}|Kommentar ID #{self.id}>",
      fields: [
        { title: 'Kommentar', value: self.text },
        { title: 'Avsender' , value: self.name, short: true },
        { title: 'E-post',    value: self.email, short: true }
      ]
    }
  end

  private

  def email_owner
    ThingsMailer.new_comment(self).deliver_later
  end

  def notify_slack
    thing = self.thing
    NotifySlackJob.perform_later "*Ny kommentar*", [
      self.as_slack_attachment,
      thing.as_slack_attachment
    ]
  end
end

app/controllers/api/comments_controller.rb
class Api::CommentsController < ApiController

  def show
    @comment = Comment.find(params[:id])

    render json: @comment
  end

  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        @thing = @comment.thing
        format.json { render json: @comment, status: :created, location: api_comment_url(@comment) }
        format.html { redirect_to "https://morgenbladet.bo/fiksefest/#/thing/#{@thing.id}" }
      else
        format.json { render json: @comment.errors, status: :unprocessable_entity }
        format.html { redirect_to "https://morgenbladet.bo/fiksefest/#/thing/#{@thing.id}" }
      end
    end
  end

  private

  def comment_params
    ActiveModelSerializers::Deserialization.jsonapi_parse(
      params, only: [:name, :email, :text, :thing_id]
    )
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment

  # PATCH /comments/1
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment.thing, notice: 'Kommentaren ble oppdatert' }
      else
        format.html { redirect_to @comment.thing, notice: 'Kommentaren kunne ikke lagres.' }
      end
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @comment.thing, notice: 'Kommentaren ble slettet.' }
    end
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:thing_id, :text, :name, :email, :published)
  end
end

app/helpers/api/comments_helper.rb
module Api::CommentsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.haml
%li.comment
  %blockquote
    = simple_format comment.text
    %footer
      = l comment.created_at, format: :long
      av
      = comment.name
      = surround '<', '>.' do
        = comment.email
      - if comment.published?
        Kommentaren er
        %span.text-success publisert.
        = link_to "Avpubliser", comment_path(id: comment.id, comment: { published: false }), method: :patch, class: %w(btn btn-warning btn-xs)
      - else
        Kommentaren er
        %span.text-warning skjult.
        = link_to "Publiser", comment_path(id: comment.id, comment: { published: true }), method: :patch, class: %w(btn btn-success btn-xs)
      = link_to "Slett", comment, method: :delete, data: { confirm: 'Er du sikker?' }, class: %w(btn btn-danger btn-xs)