config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    resources :comments, only: [ :show, :create ]
    resources :things, only: [:index, :show, :create]
  end

  devise_for :users
  resources :things do
    collection do
      get :queue
    end
  end

  resources :comments, only: [:update, :destroy]

  root to: "things#index"
end

app/models/thing.rb
class Thing < ApplicationRecord
  include ActionView::Helpers::TextHelper
  after_update :send_email, if: :just_accepted?
  after_create :notify_slack

  has_attached_file :image,
    styles: {
      tiny: "64x64#",
      small: "400x400#",
      large: "1024x1024>"
    },
    convert_options: {
      tiny: '-strip',
      small: '-strip',
      large: '-strip'
    },
    s3_protocol: :https

  validates_attachment :image,
    presence: true,
    content_type: { content_type: %w(image/jpeg image/gif image/png) },
    size: { in: 0..10.megabytes }

  process_in_background :image,
    processing_image_url: 'https://s3.eu-central-1.amazonaws.com/fiksefest/processing.png'

  validates :title, presence: true

  enum status: [ :in_queue, :accepted, :denied ]

  scope :published, -> { where(status: 'accepted') }

  has_many :comments, -> { order(created_at: :asc) }, dependent: :destroy
  has_many :published_comments,
    -> { order(created_at: :asc).where(published: true) },
    class_name: 'Comment'

  def frontend_url
    "https://morgenbladet.no/fiksefest#/thing/%s" % self.id
  end

  def as_slack_attachment
    {
      fallback: "Ting #{self.title}: #{self.frontend_url}",
      title: "Ting: <#{self.frontend_url}|#{self.title}>",
      thumb_url: self.image.url(:tiny),
      fields: [
        { title: 'Historie', value: truncate(self.description, length: 100)},
        { title: 'Innsender', value: self.owner, short: true},
        { title: 'E-post',   value: self.email, short: true}
      ]
    }
  end

  private

  def just_accepted?
    status_changed? && accepted?
  end

  def send_email
    ThingsMailer.accepted(self).deliver_later
  end

  def notify_slack
    NotifySlackJob.perform_later "Ny ting!", [ as_slack_attachment ]
  end
end

app/controllers/api/things_controller.rb
require 'slack'
class Api::ThingsController < ApiController
  def index
    @things = Thing.published.order(created_at: :desc).page(params[:page]).per(params[:per_page] || 3)

    render json: @things, include: params[:include], meta: pagination_dict(@things)
  end

  def show
    @thing = Thing.published.find(params[:id])

    render json: @thing, include: ['comments']
  end

  def create
    @thing = Thing.new(thing_params)

    respond_to do |format|
      if @thing.save
        format.json { render json: @thing, status: :created, location: api_thing_url(@thing) }
        format.html { redirect_to 'https://morgenbladet.no/fiksefest/#/takk' }
      else
        format.json { render json: @thing.errors, status: :unprocessable_entity }
        format.html { redirect_to 'https://morgenbladet.no/fiksefest/#/error' }
      end
    end
  end

  private

  def thing_params
    params.require(:thing).permit(:title, :image, :description, :owner, :email)
  end

  def pagination_dict(collection)
    {
      total_pages: collection.total_pages,
      total_count: collection.total_count,
      prev_page: collection.prev_page,
      next_page: collection.next_page,
      current_page: collection.current_page
    }
  end
end

app/controllers/things_controller.rb
require 'slack'
class ThingsController < ApplicationController
  before_action :set_thing, only: [:show, :edit, :update, :destroy]

  # GET /things
  # GET /things.json
  def index
    @things = Thing.order(:created_at).page params[:page]
  end

  def queue
    @things = Thing.in_queue.order(:created_at).page params[:page]
    @title = "Ting i moderasjonskø"
  end

  # GET /things/1
  # GET /things/1.json
  def show
  end

  # GET /things/new
  def new
    @thing = Thing.new
  end

  # GET /things/1/edit
  def edit
  end

  # POST /things
  # POST /things.json
  def create
    @thing = Thing.new(thing_params)

    respond_to do |format|
      if @thing.save
        format.html { redirect_to @thing, notice: 'Thing was successfully created.' }
        format.json { render :show, status: :created, location: @thing }
      else
        format.html { render :new }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /things/1
  # PATCH/PUT /things/1.json
  def update
    respond_to do |format|
      if @thing.update(thing_params)
        format.html { redirect_to things_path, notice: 'Tingen ble lagret!' }
        format.json { render :show, status: :ok, location: @thing }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /things/1
  # DELETE /things/1.json
  def destroy
    @thing.destroy
    respond_to do |format|
      format.html { redirect_to things_url, notice: 'Thing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thing
      @thing = Thing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thing_params
      params.require(:thing).permit(:title, :image, :description, :owner, :email, :status)
    end
end

app/helpers/things_helper.rb
module ThingsHelper
  def thing_accepted_table_class(thing)
    case thing.status
    when "accepted"
      "success"
    when "denied"
      "danger"
    when "in_queue"
      "warning"
    end
  end
end

app/views/things/_form.html.haml
= form_for @thing do |f|
  - if @thing.errors.any?
    .alert.alert-warning
      %strong Noe er galt!
      == #{@thing.errors.count} feil forhindret lagring:
      %ul
        - @thing.errors.full_messages.each do |msg|
          %li= msg

  .row
    .col-md-12
      .form-group
        = f.label :title, 'Tittel'
        = f.text_field :title, class: 'form-control input-lg'
  .row
    .col-xs-10.col-lg-11
      .form-group
        = f.label :image, (f.object.image? ? 'Erstatt bilde med' : 'Bildefil')
        = f.file_field :image, class: 'form-control'
    .col-xs-2.col-lg-1= image_tag f.object.image(:tiny) if f.object.image?
  .row
    .col-md-12
      .form-group
        = f.label :description, 'Beskrivelse'
        = f.text_area :description, class: 'form-control'
  .row
    .col-md-6
      .form-group
        = f.label :owner, 'Innsender'
        = f.text_field :owner, class: 'form-control'
    .col-md-6
      .form-group
        = f.label :email, 'E-post'
        = f.email_field :email, class: 'form-control'
  .row
    .col-md-12
      .col-md-3
        .radio
          %label
            = f.radio_button :status, "accepted", "data-toggle": "radio"
            Godkjent
      .col-md-3
        .radio
          %label
            = f.radio_button :status, "in_queue", "data-toggle": "radio"
            I moderasjonskø
      .col-md-3
        .radio
          %label
            = f.radio_button :status, "denied", "data-toggle": "radio"
            Avvist
  = f.button 'Lagre', type: :submit, class: %w(btn btn-primary btn-fill)
  = content_for :actions

app/views/things/_paginator.html.haml
= page_entries_info @things
%br
= paginate @things, remote: true, theme: 'twitter-bootstrap-3'

app/views/things/_table.html.haml
%table.table.table-hover
  %thead
    %th Bilde
    %th Tittel
    %th Innsender
    %th Dato
    %th Kommentarer
    %th
  %tbody
    = render @things

app/views/things/_thing.html.haml
%tr{class: thing_accepted_table_class(thing)}
  %td
    = link_to(thing) do
      = image_tag thing.image.url(:tiny),
        style: "width: 48px;", class: "img-thumbnail"
  %td= link_to truncate(thing.title, length: 20), thing
  %td= mail_to thing.email, thing.owner
  %td= l thing.created_at, format: :short
  %td= thing.comments.count
  %td
    = link_to 'Vis', thing, class: %w(btn btn-sm btn-primary btn-fill)
    = link_to 'Slett',
      thing,
      method: :delete,
      class: %w(btn btn-sm btn-danger),
      data: { confirm: 'Er du sikker?' }

app/views/things/edit.html.haml
- content_for :title do
  Redigere ting

.row
  .col-xs-12
    .card
      .header
        %h4.title Redigere ting
      .content
        - content_for :actions do
          = link_to 'Avbryt', @thing, class: %w(btn btn-link)
        = render 'form'

app/views/things/index.html.haml
= content_for :title do
  = @title || "Alle ting"

.row
  .col-xs-12
    .card
      .header
        = link_to 'Ny ting', new_thing_path, class: %w(btn btn-primary btn-fill btn-sm pull-right)
        %h4.title= @title || "Innsendte ting"
        %p.category Sortert etter dato

      .content
        #paginator
          = render "paginator"

      .content.table-responsive.table-full-width
        #things_table
          = render "table"

app/views/things/index.js.erb
$('#paginator').html('<%= escape_javascript(render(partial: 'things/paginator')) %>');
$('#things_table').html('<%= escape_javascript(render(partial: 'things/table')) %>');

app/views/things/new.html.haml
= content_for :title do
  Ny ting

.row
  .col-xs-12
    .card
      .header
        %h4.title Opprett ny ting
      .content
        - content_for :actions do
          = link_to 'Avbryt', things_path, class: %w(btn btn-default btn-fill)

        = render 'form'

app/views/things/queue.html.haml
- content_for :title do
  Moderasjonskø

.row
  - @things.each do |thing|
    .col-xs-12.col-md-6.col-lg-4[thing]
      .card
        .header
          %h4.title
            = link_to (thing.title || "Bilde uten tittel"), thing
          %p.category
            = thing.owner.blank? ? "Anonym" : thing.owner
            - unless thing.email.blank?
              = surround("<", ">") do
                = mail_to thing.email
        .content
          .image-text-container
            .image-text
              = simple_format truncate(thing.description, length: 400)
            = link_to thing do
              = image_tag thing.image(:small), class: "img-responsive img-rounded"
          .footer
            = form_for thing, remote: true do |f|
              .btn-group{ data: { toggle: 'buttons' } }
                = f.label :status_accepted, class: %w(btn btn-primary btn-fill) do
                  = f.radio_button :status, 'accepted', class: 'submit-on-click'
                  Godkjenn
                = f.label :status_denied, class: %w(btn btn-danger btn-fill) do
                  = f.radio_button :status, 'denied', class: 'submit-on-click'
                  Avvis
            %hr
            .stats
              %i.fa.fa-clock-o
              = l thing.created_at, format: :long

app/views/things/show.html.haml
- content_for :title do
  == Bilde (ID #{@thing.id})

.row
  .col-md-8
    .card
      .header
        %h4.title= @thing.title
        %p.category
          = succeed ": " do
            = number_to_human_size(@thing.image_file_size)
            = @thing.image_content_type
          = link_to @thing.image_file_name, @thing.image.url
      .content
        %blockquote
          = simple_format @thing.description
          %footer
            Sendt inn av
            = @thing.owner
            = surround('<', '>') do 
              = @thing.email
  .col-md-4
    .card
      .header
        %h4 Handlinger
      .content
        .btn-group(role="group")
          = link_to 'Rediger', edit_thing_path(@thing), class: %w(btn btn-primary btn-fill)
          = link_to 'Slett', @thing, method: :delete, class: %w(btn btn-danger btn-fill),
            confirm: 'Er du sikker?'
          = link_to 'Tilbake', things_path, class: %w(btn btn-default btn-fill)
    .card
      .header
        %h4 Moderering
      .content
        = form_for @thing do |f|
          .radio
            %label
              = f.radio_button :status, "accepted", data: { toggle: 'radio' }
              Godkjent
          .radio
            %label
              = f.radio_button :status, "in_queue", data: { toggle: 'radio' }
              I moderasjonskø
          .radio
            %label
              = f.radio_button :status, "denied", data: { toggle: 'radio' }
              Avvist
          = f.button 'Lagre', type: :submit, class: %w(btn btn-primary btn-fill)

.row
  .col-md-2
    .card
      .header
        %h4.title Thumb
      .content
        = image_tag @thing.image.url(:tiny), class: "img-responsive"
  .col-md-3
    .card
      .header
        %h4.title Kvadrat
      .content
        = image_tag @thing.image.url(:small), class: "img-responsive"
  .col-md-7
    .card
      .header
        %h4.title Stor
      .content
        = image_tag @thing.image.url(:large), class: "img-responsive"

.row
  .col-xs-12
    .card
      .header
        %h4.title Kommentarer
      .content
        %ul.comments
          = render(@thing.comments) || "Ingen kommentarer"

app/views/things/update.js.erb
<% unless @thing.changed? %>
  console.log("Removing <%= @thing.id %>");
  $('#thing_<%= @thing.id %>').fadeOut();
  $.notify("Statusendringen for bildet '<%= @thing.title %>' ble lagret");
<% else %>
  $.notify({
    message: "Statusendringen kunne ikke lagres!",
    title: "Feil under lagring",
    icon: "pe-7s-attention",
    url: "<%= url_for @thing %>"
  }, {
    type: 'danger'
  });
<% end %>